package model.impl.ontologyImpl.policies;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.OWLModel;
import model.interfaces.policies.ITComputingContextPolicy;


/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#ITComputingContextPolicy
 *
 * @version generated on Tue Jul 06 17:49:10 GMT 2010
 */
public class DefaultITComputingContextPolicy extends DefaultGPI_KPI_Policy
        implements ITComputingContextPolicy {

    public DefaultITComputingContextPolicy(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultITComputingContextPolicy() {
    }

    @Override
    public boolean isRespected() {
        throw new UnsupportedOperationException("Not implemented yet");
    }
}
