package model.impl.ontologyImpl.actions;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.OWLModel;
import model.impl.util.ModelAccess;
import model.interfaces.actions.ApplicationAdaptationAction;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#ApplicationAdaptationAction
 *
 * @version generated on Tue Jul 06 17:49:10 GMT 2010
 */
public class DefaultApplicationAdaptationAction extends DefaultContextAction
        implements ApplicationAdaptationAction {
        private int cost = 0;
    public int getCost() {
        return cost;
    }

    public void setCost(int cost) {
        this.cost = cost;
    }
    public DefaultApplicationAdaptationAction(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultApplicationAdaptationAction() {
    }

    @Override
    public void execute(ModelAccess modelAccess) {
        throw new UnsupportedOperationException("not implemented yet");
    }

    public void executeOnServiceCenter(ModelAccess modelAccess) {
        throw new UnsupportedOperationException("not implemented yet");    }

    @Override
    public void undo(ModelAccess modelAccess) {
        throw new UnsupportedOperationException("not implemented yet");
    }

    @Override
    public boolean equals(Object o) {
        if (!(o instanceof DefaultApplicationAdaptationAction)) {
            return false;
        }

        throw new UnsupportedOperationException("not implemented yet");
    }

     @Override
    public String toString() {
        return this.getName();
    }
}
