package model.impl.ontologyImpl.impl;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.OWLModel;
import model.impl.ontologyImpl.DefaultApplicationActivity;
import model.impl.ontologyImpl.HDDIntensiveActivity;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#HDDIntensiveActivity
 *
 * @version generated on Fri Jul 09 18:31:36 GMT 2010
 */
public class DefaultHDDIntensiveActivity extends DefaultApplicationActivity
        implements HDDIntensiveActivity {

    public DefaultHDDIntensiveActivity(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultHDDIntensiveActivity() {
    }
}
