package model.impl.ontologyImpl.impl;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.OWLModel;
import edu.stanford.smi.protegex.owl.model.RDFProperty;
import model.impl.ontologyImpl.DefaultContextAction;
import model.impl.ontologyImpl.ITComputingResourceAdaptationAction;

import java.util.Collection;
import java.util.Iterator;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#ITComputingResourceAdaptationAction
 *
 * @version generated on Fri Jul 09 18:31:36 GMT 2010
 */
public class DefaultITComputingResourceAdaptationAction extends DefaultContextAction
        implements ITComputingResourceAdaptationAction {

    public DefaultITComputingResourceAdaptationAction(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultITComputingResourceAdaptationAction() {
    }


    // Property http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#resourceFrom

    public Collection getResourceFrom() {
        return getPropertyValuesAs(getResourceFromProperty(), ServiceCenterITComputingResource.class);
    }


    public RDFProperty getResourceFromProperty() {
        final String uri = "http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#resourceFrom";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasResourceFrom() {
        return getPropertyValueCount(getResourceFromProperty()) > 0;
    }


    public Iterator listResourceFrom() {
        return listPropertyValuesAs(getResourceFromProperty(), ServiceCenterITComputingResource.class);
    }


    public void addResourceFrom(ServiceCenterITComputingResource newResourceFrom) {
        addPropertyValue(getResourceFromProperty(), newResourceFrom);
    }


    public void removeResourceFrom(ServiceCenterITComputingResource oldResourceFrom) {
        removePropertyValue(getResourceFromProperty(), oldResourceFrom);
    }


    public void setResourceFrom(Collection newResourceFrom) {
        setPropertyValues(getResourceFromProperty(), newResourceFrom);
    }


    // Property http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#resourceOn

    public Collection getResourceOn() {
        return getPropertyValuesAs(getResourceOnProperty(), ServiceCenterITComputingResource.class);
    }


    public RDFProperty getResourceOnProperty() {
        final String uri = "http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#resourceOn";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasResourceOn() {
        return getPropertyValueCount(getResourceOnProperty()) > 0;
    }


    public Iterator listResourceOn() {
        return listPropertyValuesAs(getResourceOnProperty(), ServiceCenterITComputingResource.class);
    }


    public void addResourceOn(ServiceCenterITComputingResource newResourceOn) {
        addPropertyValue(getResourceOnProperty(), newResourceOn);
    }


    public void removeResourceOn(ServiceCenterITComputingResource oldResourceOn) {
        removePropertyValue(getResourceOnProperty(), oldResourceOn);
    }


    public void setResourceOn(Collection newResourceOn) {
        setPropertyValues(getResourceOnProperty(), newResourceOn);
    }


    // Property http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#resourceTo

    public Collection getResourceTo() {
        return getPropertyValuesAs(getResourceToProperty(), ServiceCenterITComputingResource.class);
    }


    public RDFProperty getResourceToProperty() {
        final String uri = "http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#resourceTo";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasResourceTo() {
        return getPropertyValueCount(getResourceToProperty()) > 0;
    }


    public Iterator listResourceTo() {
        return listPropertyValuesAs(getResourceToProperty(), ServiceCenterITComputingResource.class);
    }


    public void addResourceTo(ServiceCenterITComputingResource newResourceTo) {
        addPropertyValue(getResourceToProperty(), newResourceTo);
    }


    public void removeResourceTo(ServiceCenterITComputingResource oldResourceTo) {
        removePropertyValue(getResourceToProperty(), oldResourceTo);
    }


    public void setResourceTo(Collection newResourceTo) {
        setPropertyValues(getResourceToProperty(), newResourceTo);
    }
}
