package model.impl.ontologyImpl.impl;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.OWLModel;
import edu.stanford.smi.protegex.owl.model.RDFProperty;
import model.impl.ontologyImpl.ContextPolicy;
import model.impl.ontologyImpl.DefaultContextElement;

import java.util.Collection;
import java.util.Iterator;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#ContextPolicy
 *
 * @version generated on Fri Jul 09 18:31:36 GMT 2010
 */
public class DefaultContextPolicy extends DefaultContextElement
        implements ContextPolicy {

    public DefaultContextPolicy(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultContextPolicy() {
    }


    // Property http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#evaluationCondition

    public String getEvaluationCondition() {
        return (String) getPropertyValue(getEvaluationConditionProperty());
    }


    public RDFProperty getEvaluationConditionProperty() {
        final String uri = "http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#evaluationCondition";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasEvaluationCondition() {
        return getPropertyValueCount(getEvaluationConditionProperty()) > 0;
    }


    public void setEvaluationCondition(String newEvaluationCondition) {
        setPropertyValue(getEvaluationConditionProperty(), newEvaluationCondition);
    }


    // Property http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#isRespected

    public boolean getIsRespected() {
        return getPropertyValueLiteral(getIsRespectedProperty()).getBoolean();
    }


    public RDFProperty getIsRespectedProperty() {
        final String uri = "http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#isRespected";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasIsRespected() {
        return getPropertyValueCount(getIsRespectedProperty()) > 0;
    }


    public void setIsRespected(boolean newIsRespected) {
        setPropertyValue(getIsRespectedProperty(), new java.lang.Boolean(newIsRespected));
    }


    // Property http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#policyName

    public String getPolicyName() {
        return (String) getPropertyValue(getPolicyNameProperty());
    }


    public RDFProperty getPolicyNameProperty() {
        final String uri = "http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#policyName";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasPolicyName() {
        return getPropertyValueCount(getPolicyNameProperty()) > 0;
    }


    public void setPolicyName(String newPolicyName) {
        setPropertyValue(getPolicyNameProperty(), newPolicyName);
    }


    // Property http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#policySubject

    public Collection getPolicySubject() {
        return getPropertyValuesAs(getPolicySubjectProperty(), ContextResource.class);
    }


    public RDFProperty getPolicySubjectProperty() {
        final String uri = "http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#policySubject";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasPolicySubject() {
        return getPropertyValueCount(getPolicySubjectProperty()) > 0;
    }


    public Iterator listPolicySubject() {
        return listPropertyValuesAs(getPolicySubjectProperty(), ContextResource.class);
    }


    public void addPolicySubject(ContextResource newPolicySubject) {
        addPropertyValue(getPolicySubjectProperty(), newPolicySubject);
    }


    public void removePolicySubject(ContextResource oldPolicySubject) {
        removePropertyValue(getPolicySubjectProperty(), oldPolicySubject);
    }


    public void setPolicySubject(Collection newPolicySubject) {
        setPropertyValues(getPolicySubjectProperty(), newPolicySubject);
    }


    // Property http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#policyTarget

    public Collection getPolicyTarget() {
        return getPropertyValuesAs(getPolicyTargetProperty(), ContextResource.class);
    }


    public RDFProperty getPolicyTargetProperty() {
        final String uri = "http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#policyTarget";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasPolicyTarget() {
        return getPropertyValueCount(getPolicyTargetProperty()) > 0;
    }


    public Iterator listPolicyTarget() {
        return listPropertyValuesAs(getPolicyTargetProperty(), ContextResource.class);
    }


    public void addPolicyTarget(ContextResource newPolicyTarget) {
        addPropertyValue(getPolicyTargetProperty(), newPolicyTarget);
    }


    public void removePolicyTarget(ContextResource oldPolicyTarget) {
        removePropertyValue(getPolicyTargetProperty(), oldPolicyTarget);
    }


    public void setPolicyTarget(Collection newPolicyTarget) {
        setPropertyValues(getPolicyTargetProperty(), newPolicyTarget);
    }
}
