package model.impl.ontologyImpl.impl;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.OWLModel;
import model.impl.ontologyImpl.CPUIntensiveActivity;
import model.impl.ontologyImpl.DefaultApplicationActivity;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#CPUIntensiveActivity
 *
 * @version generated on Fri Jul 09 18:31:36 GMT 2010
 */
public class DefaultCPUIntensiveActivity extends DefaultApplicationActivity
        implements CPUIntensiveActivity {

    public DefaultCPUIntensiveActivity(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultCPUIntensiveActivity() {
    }
}
