package model.impl.ontologyImpl.impl;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.OWLModel;
import edu.stanford.smi.protegex.owl.model.RDFProperty;
import model.impl.ontologyImpl.DefaultContextPolicy;
import model.impl.ontologyImpl.GPI_KPI_Policy;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#GPI_KPI_Policy
 *
 * @version generated on Fri Jul 09 18:31:36 GMT 2010
 */
public class DefaultGPI_KPI_Policy extends DefaultContextPolicy
        implements GPI_KPI_Policy {

    public DefaultGPI_KPI_Policy(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultGPI_KPI_Policy() {
    }


    // Property http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#hasAttached

    public Object getHasAttached() {
        return (Object) getPropertyValue(getHasAttachedProperty());
    }


    public RDFProperty getHasAttachedProperty() {
        final String uri = "http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#hasAttached";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasHasAttached() {
        return getPropertyValueCount(getHasAttachedProperty()) > 0;
    }


    public void setHasAttached(Object newHasAttached) {
        setPropertyValue(getHasAttachedProperty(), newHasAttached);
    }


    // Property http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#policyAction

    public ContextAction getPolicyAction() {
        return (ContextAction) getPropertyValueAs(getPolicyActionProperty(), ContextAction.class);
    }


    public RDFProperty getPolicyActionProperty() {
        final String uri = "http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#policyAction";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasPolicyAction() {
        return getPropertyValueCount(getPolicyActionProperty()) > 0;
    }


    public void setPolicyAction(ContextAction newPolicyAction) {
        setPropertyValue(getPolicyActionProperty(), newPolicyAction);
    }
}
