package model.impl.ontologyImpl.impl;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.OWLModel;
import edu.stanford.smi.protegex.owl.model.RDFProperty;
import model.impl.ontologyImpl.DefaultConsolidationAction;
import model.impl.ontologyImpl.DeployActivity;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#DeployActivity
 *
 * @version generated on Fri Jul 09 18:31:36 GMT 2010
 */
public class DefaultDeployActivity extends DefaultConsolidationAction
        implements DeployActivity {

    public DefaultDeployActivity(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultDeployActivity() {
    }


    // Property http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#activity

    public ApplicationActivity getActivity() {
        return (ApplicationActivity) getPropertyValueAs(getActivityProperty(), ApplicationActivity.class);
    }


    public RDFProperty getActivityProperty() {
        final String uri = "http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#activity";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasActivity() {
        return getPropertyValueCount(getActivityProperty()) > 0;
    }


    public void setActivity(ApplicationActivity newActivity) {
        setPropertyValue(getActivityProperty(), newActivity);
    }


    // Property http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#resourceTo

    public ServiceCenterITComputingResource getResourceTo() {
        return (ServiceCenterITComputingResource) getPropertyValueAs(getResourceToProperty(), ServiceCenterITComputingResource.class);
    }


    public RDFProperty getResourceToProperty() {
        final String uri = "http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#resourceTo";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasResourceTo() {
        return getPropertyValueCount(getResourceToProperty()) > 0;
    }


    public void setResourceTo(ServiceCenterITComputingResource newResourceTo) {
        setPropertyValue(getResourceToProperty(), newResourceTo);
    }
}
