package testOntology;

import com.hp.hpl.jena.ontology.OntModel;
import edu.stanford.smi.protegex.owl.model.OWLIndividual;
import edu.stanford.smi.protegex.owl.model.RDFProperty;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/Ontology1282633635.owl#Test
 *
 * @version generated on Tue Aug 24 10:09:10 EEST 2010
 */
public interface Test extends OWLIndividual {

    // Property http://www.owl-ontologies.com/Ontology1282633635.owl#testValue

    int getTestValue(OntModel model);

    RDFProperty getTestValueProperty();

    boolean hasTestValue();

    void setTestValue(int newTestValue, OntModel model);
}
