package model.impl.ontologyImpl.resources.applications;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.OWLModel;
import model.interfaces.resources.applications.HDDIntensiveActivity;


/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#HDDIntensiveActivity
 *
 * @version generated on Tue Jul 06 17:49:10 GMT 2010
 */
public class DefaultHDDIntensiveActivity extends DefaultApplicationActivity
        implements HDDIntensiveActivity {

    public DefaultHDDIntensiveActivity(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultHDDIntensiveActivity() {
    }
}
