package model.impl.ontologyImpl.impl;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.javacode.AbstractCodeGeneratorIndividual;
import edu.stanford.smi.protegex.owl.model.OWLModel;
import model.impl.ontologyImpl.ContextElement;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#ContextElement
 *
 * @version generated on Fri Jul 09 18:31:36 GMT 2010
 */
public class DefaultContextElement extends AbstractCodeGeneratorIndividual
        implements ContextElement {

    public DefaultContextElement(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultContextElement() {
    }
}
