package model.impl.ontologyImpl.policies;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.OWLModel;
import model.interfaces.policies.QoSPolicy;


/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#QoSPolicy
 *
 * @version generated on Tue Jul 06 17:49:11 GMT 2010
 */
public class DefaultQoSPolicy extends DefaultBusinessPolicy
        implements QoSPolicy {

    public DefaultQoSPolicy(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultQoSPolicy() {
    }

    @Override
    public boolean isRespected() {
        throw new UnsupportedOperationException("Not implemented yet");
    }
}
