package model.interfaces.actions;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#FacilityDefaultAction
 *
 * @version generated on Thu Aug 12 06:33:35 GMT 2010
 */
public interface FacilityDefaultAction extends ContextAction {
}
