package model.impl.ontologyImpl;

import edu.stanford.smi.protegex.owl.model.RDFProperty;

import java.util.Collection;
import java.util.Iterator;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#ComplexResource
 *
 * @version generated on Fri Jul 09 18:31:36 GMT 2010
 */
public interface ComplexResource extends ServiceCenterITComputingResource {

    // Property http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#resourceWorkloadProperty

    Collection getResourceWorkloadProperty();

    RDFProperty getResourceWorkloadPropertyProperty();

    boolean hasResourceWorkloadProperty();

    Iterator listResourceWorkloadProperty();

    void addResourceWorkloadProperty(String newResourceWorkloadProperty);

    void removeResourceWorkloadProperty(String oldResourceWorkloadProperty);

    void setResourceWorkloadProperty(Collection newResourceWorkloadProperty);


    // Property http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#simpleResources

    Collection getSimpleResources();

    RDFProperty getSimpleResourcesProperty();

    boolean hasSimpleResources();

    Iterator listSimpleResources();

    void addSimpleResources(SimpleResource newSimpleResources);

    void removeSimpleResources(SimpleResource oldSimpleResources);

    void setSimpleResources(Collection newSimpleResources);
}
