package model.impl.ontologyImpl;

import edu.stanford.smi.protegex.owl.model.RDFProperty;

import java.util.Collection;
import java.util.Iterator;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#ContextAction
 *
 * @version generated on Fri Jul 09 18:31:36 GMT 2010
 */
public interface ContextAction extends ContextElement {

    // Property http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#activity

    Collection getActivity();

    RDFProperty getActivityProperty();

    boolean hasActivity();

    Iterator listActivity();

    void addActivity(ApplicationActivity newActivity);

    void removeActivity(ApplicationActivity oldActivity);

    void setActivity(Collection newActivity);


    // Property http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#associatedResources

    Collection getAssociatedResources();

    RDFProperty getAssociatedResourcesProperty();

    boolean hasAssociatedResources();

    Iterator listAssociatedResources();

    void addAssociatedResources(ContextResource newAssociatedResources);

    void removeAssociatedResources(ContextResource oldAssociatedResources);

    void setAssociatedResources(Collection newAssociatedResources);


    // Property http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#resources

    Collection getResources();

    RDFProperty getResourcesProperty();

    boolean hasResources();

    Iterator listResources();

    void addResources(ContextResource newResources);

    void removeResources(ContextResource oldResources);

    void setResources(Collection newResources);
}
