package model.impl.ontologyImpl;

import edu.stanford.smi.protegex.owl.model.RDFProperty;

import java.util.Collection;
import java.util.Iterator;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#ITFacilityResourceAdaptationAction
 *
 * @version generated on Fri Jul 09 18:31:36 GMT 2010
 */
public interface ITFacilityResourceAdaptationAction extends ContextAction {

    // Property http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#associatedResources

    Collection getAssociatedResources();

    RDFProperty getAssociatedResourcesProperty();

    boolean hasAssociatedResources();

    Iterator listAssociatedResources();

    void addAssociatedResources(ContextResource newAssociatedResources);

    void removeAssociatedResources(ContextResource oldAssociatedResources);

    void setAssociatedResources(Collection newAssociatedResources);


    // Property http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#facilityAction

    ContextAction getFacilityAction();

    RDFProperty getFacilityActionProperty();

    boolean hasFacilityAction();

    void setFacilityAction(ContextAction newFacilityAction);


    // Property http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#interractsWith

    Collection getInterractsWith();

    RDFProperty getInterractsWithProperty();

    boolean hasInterractsWith();

    Iterator listInterractsWith();

    void addInterractsWith(ITFacilityActiveResource newInterractsWith);

    void removeInterractsWith(ITFacilityActiveResource oldInterractsWith);

    void setInterractsWith(Collection newInterractsWith);
}
