package model.impl.ontologyImpl;

import edu.stanford.smi.protegex.owl.model.RDFProperty;

import java.util.Collection;
import java.util.Iterator;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#ITFacilityActiveResource
 *
 * @version generated on Fri Jul 09 18:31:36 GMT 2010
 */
public interface ITFacilityActiveResource extends ServiceCenterITFacilityResource {

    // Property http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#associatedActions

    Collection getAssociatedActions();

    RDFProperty getAssociatedActionsProperty();

    boolean hasAssociatedActions();

    Iterator listAssociatedActions();

    void addAssociatedActions(ITFacilityResourceAdaptationAction newAssociatedActions);

    void removeAssociatedActions(ITFacilityResourceAdaptationAction oldAssociatedActions);

    void setAssociatedActions(Collection newAssociatedActions);
}
