package model.impl.ontologyImpl;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#ApplicationRedesign
 *
 * @version generated on Fri Jul 09 18:31:36 GMT 2010
 */
public interface ApplicationRedesign extends ApplicationAdaptationAction {
}
