package model.impl.ontologyImpl;

import edu.stanford.smi.protegex.owl.model.RDFProperty;

import java.util.Collection;
import java.util.Iterator;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#Application
 *
 * @version generated on Fri Jul 09 18:31:36 GMT 2010
 */
public interface Application extends BusinessContextResource {

    // Property http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#BP_ActivityList

    Collection getBP_ActivityList();

    RDFProperty getBP_ActivityListProperty();

    boolean hasBP_ActivityList();

    Iterator listBP_ActivityList();

    void addBP_ActivityList(ApplicationActivity newBP_ActivityList);

    void removeBP_ActivityList(ApplicationActivity oldBP_ActivityList);

    void setBP_ActivityList(Collection newBP_ActivityList);
}
