package model.impl.ontologyImpl;

import edu.stanford.smi.protegex.owl.model.OWLIndividual;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#ContextElement
 *
 * @version generated on Fri Jul 09 18:31:36 GMT 2010
 */
public interface ContextElement extends OWLIndividual {
}
