package model.impl.ontologyImpl;

import edu.stanford.smi.protegex.owl.model.RDFProperty;

import java.util.Collection;
import java.util.Iterator;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#ContextPolicy
 *
 * @version generated on Fri Jul 09 18:31:36 GMT 2010
 */
public interface ContextPolicy extends ContextElement {

    // Property http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#evaluationCondition

    String getEvaluationCondition();

    RDFProperty getEvaluationConditionProperty();

    boolean hasEvaluationCondition();

    void setEvaluationCondition(String newEvaluationCondition);


    // Property http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#isRespected

    boolean getIsRespected();

    RDFProperty getIsRespectedProperty();

    boolean hasIsRespected();

    void setIsRespected(boolean newIsRespected);


    // Property http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#policyName

    String getPolicyName();

    RDFProperty getPolicyNameProperty();

    boolean hasPolicyName();

    void setPolicyName(String newPolicyName);


    // Property http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#policySubject

    Collection getPolicySubject();

    RDFProperty getPolicySubjectProperty();

    boolean hasPolicySubject();

    Iterator listPolicySubject();

    void addPolicySubject(ContextResource newPolicySubject);

    void removePolicySubject(ContextResource oldPolicySubject);

    void setPolicySubject(Collection newPolicySubject);


    // Property http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#policyTarget

    Collection getPolicyTarget();

    RDFProperty getPolicyTargetProperty();

    boolean hasPolicyTarget();

    Iterator listPolicyTarget();

    void addPolicyTarget(ContextResource newPolicyTarget);

    void removePolicyTarget(ContextResource oldPolicyTarget);

    void setPolicyTarget(Collection newPolicyTarget);
}
