package model.impl.ontologyImpl;

import edu.stanford.smi.protegex.owl.model.RDFProperty;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#DeployActivity
 *
 * @version generated on Fri Jul 09 18:31:36 GMT 2010
 */
public interface DeployActivity extends ConsolidationAction {

    // Property http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#activity

    ApplicationActivity getActivity();

    RDFProperty getActivityProperty();

    boolean hasActivity();

    void setActivity(ApplicationActivity newActivity);


    // Property http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#resourceTo

    ServiceCenterITComputingResource getResourceTo();

    RDFProperty getResourceToProperty();

    boolean hasResourceTo();

    void setResourceTo(ServiceCenterITComputingResource newResourceTo);
}
