package model.impl.ontologyImpl;

import edu.stanford.smi.protegex.owl.model.RDFProperty;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#DPMAction
 *
 * @version generated on Fri Jul 09 18:31:36 GMT 2010
 */
public interface DPMAction extends ITComputingResourceAdaptationAction {

    // Property http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#noStatesJump

    int getNoStatesJump();

    RDFProperty getNoStatesJumpProperty();

    boolean hasNoStatesJump();

    void setNoStatesJump(int newNoStatesJump);


    // Property http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#resourceOn

    ServiceCenterITComputingResource getResourceOn();

    RDFProperty getResourceOnProperty();

    boolean hasResourceOn();

    void setResourceOn(ServiceCenterITComputingResource newResourceOn);


    // Property http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#stateAfterAction

    int getStateAfterAction();

    RDFProperty getStateAfterActionProperty();

    boolean hasStateAfterAction();

    void setStateAfterAction(int newStateAfterAction);


    // Property http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#stateBeforeAction

    int getStateBeforeAction();

    RDFProperty getStateBeforeActionProperty();

    boolean hasStateBeforeAction();

    void setStateBeforeAction(int newStateBeforeAction);


    // Property http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#toLowOrHighState

    boolean getToLowOrHighState();

    RDFProperty getToLowOrHighStateProperty();

    boolean hasToLowOrHighState();

    void setToLowOrHighState(boolean newToLowOrHighState);
}
