package model.impl.ontologyImpl;

import edu.stanford.smi.protegex.owl.model.RDFProperty;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#GPI_KPI_Policy
 *
 * @version generated on Fri Jul 09 18:31:36 GMT 2010
 */
public interface GPI_KPI_Policy extends ContextPolicy {

    // Property http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#hasAttached

    Object getHasAttached();

    RDFProperty getHasAttachedProperty();

    boolean hasHasAttached();

    void setHasAttached(Object newHasAttached);


    // Property http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#policyAction

    ContextAction getPolicyAction();

    RDFProperty getPolicyActionProperty();

    boolean hasPolicyAction();

    void setPolicyAction(ContextAction newPolicyAction);
}
