package model.impl.ontologyImpl;

import edu.stanford.smi.protegex.owl.model.RDFProperty;

import java.util.Collection;
import java.util.Iterator;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#HDD
 *
 * @version generated on Fri Jul 09 18:31:36 GMT 2010
 */
public interface HDD extends SimpleResource {

    // Property http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#partOf

    Collection getPartOf();

    RDFProperty getPartOfProperty();

    boolean hasPartOf();

    Iterator listPartOf();

    void addPartOf(ContextElement newPartOf);

    void removePartOf(ContextElement oldPartOf);

    void setPartOf(Collection newPartOf);


    // Property http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#rotationSpeed

    Collection getRotationSpeed();

    RDFProperty getRotationSpeedProperty();

    boolean hasRotationSpeed();

    Iterator listRotationSpeed();

    void addRotationSpeed(float newRotationSpeed);

    void removeRotationSpeed(float oldRotationSpeed);

    void setRotationSpeed(Collection newRotationSpeed);
}
