package model.impl.ontologyImpl;

import edu.stanford.smi.protegex.owl.model.RDFProperty;

import java.util.Collection;
import java.util.Iterator;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#MEM
 *
 * @version generated on Fri Jul 09 18:31:36 GMT 2010
 */
public interface MEM extends SimpleResource {

    // Property http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#cacheRate

    Collection getCacheRate();

    RDFProperty getCacheRateProperty();

    boolean hasCacheRate();

    Iterator listCacheRate();

    void addCacheRate(float newCacheRate);

    void removeCacheRate(float oldCacheRate);

    void setCacheRate(Collection newCacheRate);


    // Property http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#clockRate

    Collection getClockRate();

    RDFProperty getClockRateProperty();

    boolean hasClockRate();

    Iterator listClockRate();

    void addClockRate(float newClockRate);

    void removeClockRate(float oldClockRate);

    void setClockRate(Collection newClockRate);


    // Property http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#partOf

    Collection getPartOf();

    RDFProperty getPartOfProperty();

    boolean hasPartOf();

    Iterator listPartOf();

    void addPartOf(ContextElement newPartOf);

    void removePartOf(ContextElement oldPartOf);

    void setPartOf(Collection newPartOf);
}
