package model.impl.ontologyImpl.resources;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.OWLModel;
import edu.stanford.smi.protegex.owl.model.RDFProperty;
import model.impl.ontologyImpl.DefaultContextElement;
import model.interfaces.resources.ContextResource;


/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#ContextResource
 *
 * @version generated on Tue Jul 06 17:49:10 GMT 2010
 */
public class DefaultContextResource extends DefaultContextElement
        implements ContextResource {

    public DefaultContextResource(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultContextResource() {
    }


    // Property http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#resourceID

    public String getResourceID() {
        return (String) getPropertyValue(getResourceIDProperty());
    }


    public RDFProperty getResourceIDProperty() {
        final String uri = "http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#resourceID";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasResourceID() {
        return getPropertyValueCount(getResourceIDProperty()) > 0;
    }


    public void setResourceID(String newResourceID) {
        setPropertyValue(getResourceIDProperty(), newResourceID);
    }
}
