package model.interfaces.actions;

import edu.stanford.smi.protegex.owl.model.RDFProperty;
import model.interfaces.actions.ConsolidationAction;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#SetServerStateAction
 *
 * @version generated on Tue Aug 10 06:52:17 GMT 2010
 */
public interface SetServerStateAction extends ConsolidationAction {
    //TODO: nu object k range pe ServiceNushCe :P
    // Property http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#targetResource

    Object getTargetResource();

    RDFProperty getTargetResourceProperty();

    boolean hasTargetResource();

    void setTargetResource(Object newTargetResource);
}
