package model.interfaces.actions;

import edu.stanford.smi.protegex.owl.model.RDFProperty;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#SetServerStateActivity
 *
 * @version generated on Tue Aug 10 06:52:17 GMT 2010
 */
public interface SetServerStateActivity extends ConsolidationAction {
    // Property http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#targetServerState

    int getTargetServerState();

    void setTargetServerState(int newTargetServerState);
}
