package model.impl.ontologyImpl;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.OWLModel;
import edu.stanford.smi.protegex.owl.model.RDFProperty;
import model.interfaces.actions.ITFacilityResourceAdaptationAction;
import model.interfaces.resources.ITFacilityActiveResource;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;
import java.util.List;


/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#ITFacilityActiveResource
 *
 * @version generated on Tue Jul 06 17:49:10 GMT 2010
 */
public class DefaultITFacilityActiveResource extends DefaultServiceCenterITFacilityResource
        implements ITFacilityActiveResource {

    public DefaultITFacilityActiveResource(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultITFacilityActiveResource() {
    }


    // Property http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#associatedActions

    public Collection getAssociatedActions() {
        return getPropertyValuesAs(getAssociatedActionsProperty(), ITFacilityResourceAdaptationAction.class);
    }


    public RDFProperty getAssociatedActionsProperty() {
        final String uri = "http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#associatedActions";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasAssociatedActions() {
        return getPropertyValueCount(getAssociatedActionsProperty()) > 0;
    }


    public Iterator listAssociatedActions() {
        return listPropertyValuesAs(getAssociatedActionsProperty(), ITFacilityResourceAdaptationAction.class);
    }


    public void addAssociatedAction(ITFacilityResourceAdaptationAction newAssociatedActions) {
        addPropertyValue(getAssociatedActionsProperty(), newAssociatedActions);
    }


    public void removeAssociatedAction(ITFacilityResourceAdaptationAction oldAssociatedActions) {
        removePropertyValue(getAssociatedActionsProperty(), oldAssociatedActions);
    }


    public void setAssociatedActions(List<ITFacilityResourceAdaptationAction> actions) {
        setPropertyValues(getAssociatedActionsProperty(), actions);
    }

    public List<ITFacilityResourceAdaptationAction> getActions() {

        return new ArrayList<ITFacilityResourceAdaptationAction>(getAssociatedActions());

    }


}
