package model.impl.ontologyImpl;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.OWLModel;
import model.interfaces.actions.FacilityDefaultAction;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#FacilityDefaultAction
 *
 * @version generated on Thu Aug 12 06:33:35 GMT 2010
 */
public class DefaultFacilityDefaultAction extends DefaultContextAction
        implements FacilityDefaultAction {

    public DefaultFacilityDefaultAction(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultFacilityDefaultAction() {
    }
}
