package model.impl.ontologyImpl;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.OWLModel;
import edu.stanford.smi.protegex.owl.model.RDFProperty;
import model.interfaces.resources.ITFacilityPassiveResource;


/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#ITFacilityPassiveResource
 *
 * @version generated on Tue Jul 06 17:49:10 GMT 2010
 */
public class DefaultITFacilityPassiveResource extends DefaultServiceCenterITFacilityResource
        implements ITFacilityPassiveResource {

    public DefaultITFacilityPassiveResource(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultITFacilityPassiveResource() {
    }


    // Property http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#recordedValue

    public Double getRecordedValue() {
        return getPropertyValueLiteral(getRecordedValueProperty()).getDouble();
    }


    public RDFProperty getRecordedValueProperty() {
        final String uri = "http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#recordedValue";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasRecordedValue() {
        return getPropertyValueCount(getRecordedValueProperty()) > 0;
    }


    public void setRecordedValue(Double newRecordedValue) {
        setPropertyValue(getRecordedValueProperty(), new java.lang.Float(newRecordedValue));
    }
}
