package model.impl.ontologyImpl;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.OWLModel;
import edu.stanford.smi.protegex.owl.model.RDFProperty;
import model.interfaces.resources.ServiceCenterITFacilityResource;

import java.util.Collection;
import java.util.Iterator;


/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#ServiceCenterITFacilityResource
 *
 * @version generated on Tue Jul 06 17:49:10 GMT 2010
 */
public class DefaultServiceCenterITFacilityResource extends DefaultContextResource
        implements ServiceCenterITFacilityResource {

    public DefaultServiceCenterITFacilityResource(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultServiceCenterITFacilityResource() {
    }


    // Property http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#hasAssociatedActions

    public Collection getHasAssociatedActions() {
        return getPropertyValues(getHasAssociatedActionsProperty());
    }


    public RDFProperty getHasAssociatedActionsProperty() {
        final String uri = "http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#hasAssociatedActions";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasHasAssociatedActions() {
        return getPropertyValueCount(getHasAssociatedActionsProperty()) > 0;
    }


    public Iterator listHasAssociatedActions() {
        return listPropertyValues(getHasAssociatedActionsProperty());
    }


    public void addHasAssociatedActions(boolean newHasAssociatedActions) {
        addPropertyValue(getHasAssociatedActionsProperty(), newHasAssociatedActions);
    }


    public void removeHasAssociatedActions(boolean oldHasAssociatedActions) {
        removePropertyValue(getHasAssociatedActionsProperty(), oldHasAssociatedActions);
    }


    public void setHasAssociatedActions(Collection newHasAssociatedActions) {
        setPropertyValues(getHasAssociatedActionsProperty(), newHasAssociatedActions);
    }


    // Property http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#resourceProperty

    public String getResourceProperty() {
        return (String) getPropertyValue(getResourcePropertyProperty());
    }


    public RDFProperty getResourcePropertyProperty() {
        final String uri = "http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#resourceProperty";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasResourceProperty() {
        return getPropertyValueCount(getResourcePropertyProperty()) > 0;
    }


    public void setResourceProperty(String newResourceProperty) {
        setPropertyValue(getResourcePropertyProperty(), newResourceProperty);
    }
}
