package model.impl.ontologyImpl;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.OWLModel;
import model.interfaces.resources.ServiceCenterServer;


/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#ServiceCenterServer
 *
 * @version generated on Tue Jul 06 17:49:10 GMT 2010
 */
public class DefaultServiceCenterServer extends DefaultComplexResource
        implements ServiceCenterServer {

    public DefaultServiceCenterServer(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultServiceCenterServer() {
    }
}
