package model.impl.ontologyImpl;

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.OWLModel;
import edu.stanford.smi.protegex.owl.model.RDFProperty;
import model.interfaces.policies.BusinessPolicy;
import model.interfaces.resources.BusinessContextResource;

import java.util.Collection;
import java.util.Iterator;


/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#BusinessContextResource
 *
 * @version generated on Tue Jul 06 17:49:10 GMT 2010
 */
public class DefaultBusinessContextResource extends DefaultContextResource
        implements BusinessContextResource {

    public DefaultBusinessContextResource(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }


    public DefaultBusinessContextResource() {
    }


    // Property http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#activityPolicies

    public Collection getActivityPolicies() {
        return getPropertyValuesAs(getActivityPoliciesProperty(), BusinessPolicy.class);
    }


    public RDFProperty getActivityPoliciesProperty() {
        final String uri = "http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#activityPolicies";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasActivityPolicies() {
        return getPropertyValueCount(getActivityPoliciesProperty()) > 0;
    }


    public Iterator listActivityPolicies() {
        return listPropertyValuesAs(getActivityPoliciesProperty(), BusinessPolicy.class);
    }


    public void addActivityPolicies(BusinessPolicy newActivityPolicies) {
        addPropertyValue(getActivityPoliciesProperty(), newActivityPolicies);
    }


    public void removeActivityPolicies(BusinessPolicy oldActivityPolicies) {
        removePropertyValue(getActivityPoliciesProperty(), oldActivityPolicies);
    }


    public void setActivityPolicies(Collection newActivityPolicies) {
        setPropertyValues(getActivityPoliciesProperty(), newActivityPolicies);
    }


    // Property http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#cpuAllocatedValue

    public Double getCpuAllocatedValue() {
        return getPropertyValueLiteral(getCpuAllocatedValueProperty()).getDouble();
    }


    public RDFProperty getCpuAllocatedValueProperty() {
        final String uri = "http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#cpuAllocatedValue";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasCpuAllocatedValue() {
        return getPropertyValueCount(getCpuAllocatedValueProperty()) > 0;
    }


    public void setCpuAllocatedValue(Double newCpuAllocatedValue) {
        setPropertyValue(getCpuAllocatedValueProperty(), new java.lang.Float(newCpuAllocatedValue));
    }


    // Property http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#cpuRequiredValue

    public Double getCpuRequiredValue() {
        return getPropertyValueLiteral(getCpuRequiredValueProperty()).getDouble();
    }


    public RDFProperty getCpuRequiredValueProperty() {
        final String uri = "http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#cpuRequiredValue";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasCpuRequiredValue() {
        return getPropertyValueCount(getCpuRequiredValueProperty()) > 0;
    }


    public void setCpuRequiredValue(Double newCpuRequiredValue) {
        setPropertyValue(getCpuRequiredValueProperty(), new java.lang.Float(newCpuRequiredValue));
    }


    // Property http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#hddAllocatedValue

    public Double getHddAllocatedValue() {
        return getPropertyValueLiteral(getHddAllocatedValueProperty()).getDouble();
    }


    public RDFProperty getHddAllocatedValueProperty() {
        final String uri = "http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#hddAllocatedValue";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasHddAllocatedValue() {
        return getPropertyValueCount(getHddAllocatedValueProperty()) > 0;
    }


    public void setHddAllocatedValue(Double newHddAllocatedValue) {
        setPropertyValue(getHddAllocatedValueProperty(), new java.lang.Float(newHddAllocatedValue));
    }


    // Property http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#hddRequiredValue

    public Double getHddRequiredValue() {
        return getPropertyValueLiteral(getHddRequiredValueProperty()).getDouble();
    }


    public RDFProperty getHddRequiredValueProperty() {
        final String uri = "http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#hddRequiredValue";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasHddRequiredValue() {
        return getPropertyValueCount(getHddRequiredValueProperty()) > 0;
    }


    public void setHddRequiredValue(Double newHddRequiredValue) {
        setPropertyValue(getHddRequiredValueProperty(), new java.lang.Float(newHddRequiredValue));
    }


    // Property http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#memAllocatedValue

    public Double getMemAllocatedValue() {
        return getPropertyValueLiteral(getMemAllocatedValueProperty()).getDouble();
    }


    public RDFProperty getMemAllocatedValueProperty() {
        final String uri = "http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#memAllocatedValue";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasMemAllocatedValue() {
        return getPropertyValueCount(getMemAllocatedValueProperty()) > 0;
    }


    public void setMemAllocatedValue(Double newMemAllocatedValue) {
        setPropertyValue(getMemAllocatedValueProperty(), new java.lang.Float(newMemAllocatedValue));
    }


    // Property http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#memRequiredValue

    public Double getMemRequiredValue() {
        return getPropertyValueLiteral(getMemRequiredValueProperty()).getDouble();
    }


    public RDFProperty getMemRequiredValueProperty() {
        final String uri = "http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#memRequiredValue";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasMemRequiredValue() {
        return getPropertyValueCount(getMemRequiredValueProperty()) > 0;
    }


    public void setMemRequiredValue(Double newMemRequiredValue) {
        setPropertyValue(getMemRequiredValueProperty(), new java.lang.Float(newMemRequiredValue));
    }


    // Property http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#numberOfCoresAllocatedValue

    public float getNumberOfCoresAllocatedValue() {
        return getPropertyValueLiteral(getNumberOfCoresAllocatedValueProperty()).getFloat();
    }


    public RDFProperty getNumberOfCoresAllocatedValueProperty() {
        final String uri = "http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#numberOfCoresAllocatedValue";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasNumberOfCoresAllocatedValue() {
        return getPropertyValueCount(getNumberOfCoresAllocatedValueProperty()) > 0;
    }


    public void setNumberOfCoresAllocatedValue(float newNumberOfCoresAllocatedValue) {
        setPropertyValue(getNumberOfCoresAllocatedValueProperty(), new java.lang.Float(newNumberOfCoresAllocatedValue));
    }


    // Property http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#numberOfCoresRequiredValue

    public float getNumberOfCoresRequiredValue() {
        return getPropertyValueLiteral(getNumberOfCoresRequiredValueProperty()).getFloat();
    }


    public RDFProperty getNumberOfCoresRequiredValueProperty() {
        final String uri = "http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#numberOfCoresRequiredValue";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasNumberOfCoresRequiredValue() {
        return getPropertyValueCount(getNumberOfCoresRequiredValueProperty()) > 0;
    }


    public void setNumberOfCoresRequiredValue(float newNumberOfCoresRequiredValue) {
        setPropertyValue(getNumberOfCoresRequiredValueProperty(), new java.lang.Float(newNumberOfCoresRequiredValue));
    }


    // Property http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#performanceDegradation

    public Double getPerformanceDegradation() {
        return getPropertyValueLiteral(getPerformanceDegradationProperty()).getDouble();
    }


    public RDFProperty getPerformanceDegradationProperty() {
        final String uri = "http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#performanceDegradation";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasPerformanceDegradation() {
        return getPropertyValueCount(getPerformanceDegradationProperty()) > 0;
    }


    public void setPerformanceDegradation(Double newPerformanceDegradation) {
        setPropertyValue(getPerformanceDegradationProperty(), new java.lang.Float(newPerformanceDegradation));
    }


    // Property http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#performanceEstimation

    public Double getPerformanceEstimation() {
        return getPropertyValueLiteral(getPerformanceEstimationProperty()).getDouble();
    }


    public RDFProperty getPerformanceEstimationProperty() {
        final String uri = "http://www.semanticweb.org/ontologies/2010/6/ContextModel.owl#performanceEstimation";
        final String name = getOWLModel().getResourceNameForURI(uri);
        return getOWLModel().getRDFProperty(name);
    }


    public boolean hasPerformanceEstimation() {
        return getPropertyValueCount(getPerformanceEstimationProperty()) > 0;
    }


    public void setPerformanceEstimation(Double newPerformanceEstimation) {
        setPropertyValue(getPerformanceEstimationProperty(), new java.lang.Float(newPerformanceEstimation));
    }
}
